# Site settings
title: PyData Osaka
description:
  大阪のPython科学技術スタックのユーザーと開発者のコミュニティ

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://osaka.pydata.org" # the base hostname & protocol for your site


future: true

tickets_url: https://www.eventbrite.com/e/pydata-eindhoven-2020-tickets-117358340957
schedule_url: https://pydata.org/eindhoven2020/schedule/
cfp_url:

dates:
location:

greeting:
  title: PyData Osakaについて
  text:
    PyData Osakaはデータエンジニアやデータサイエンティストのコミュニティです。
    このウェブサイトでは、大阪でのPyData関連の活動の概要を説明しています。
    私たちの取り組みに参加し、大阪で強力なPyDataコミュニティを構築することをサポートしてください！<br /><br />

social:
  twitter: https://twitter.com/pydataosaka
  github: https://github.com/pydataosaka

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

include: ['_pages']

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/pydataosaka
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/pydataosaka

# Build settings
markdown: kramdown

destination: ./build
